Travis ci
quizlet/hammock pull request #14
Opened 2019-12-06 20:30 UTC by lexidor

2019-12-06 20:36 UTC, lexidor commented
![image](https://user-images.githubusercontent.com/31805625/70354607-4ae2c200-1870-11ea-82dc-74038f660c72.png)
I can't turn on travis for the quizlet one. According to @azjezz that requires someone with write access. The files I can supply, however.

2019-12-06 20:38 UTC, lexidor commented
Fixes #9

2019-12-06 20:51 UTC, azjezz requested changes

2019-12-06 20:51 UTC, azjezz commented on .travis.yml
> +language: generic
```suggestion
language: shell
```

2019-12-06 20:51 UTC, azjezz commented on .travis.yml
> +sudo: required
sudo is deprecated and has no effects

2019-12-09 18:52 UTC, merged

2019-12-10 21:51 UTC, tyronjung-quizlet commented
Thanks for your help @azjezz!